[watcher]
root = "./src"
match = "all"
ignore = ["**/.git/**"]
log_json = false

[[rule]]
extensions = ["odin"]
command = "odin build . -out:main.exe"
workdir = "src"

[[rule]]
pattern = "src/test/**/*.odin"
command = "odin build ${file} -file"
# workdir omitted => event dir
